name: insightq
description: Insight Questionnaire

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 0.5.6+3
  rxdart: ^0.23.1
  http: 0.12.0+4
  toast: ^0.1.5
  intl: ^0.16.1
  firebase_auth: ^0.15.5+2
  google_sign_in: ^4.1.0
  googleapis: ^0.54.0
  googleapis_auth: ^0.2.11
  path_provider: ^1.6.5
  file_picker: ^1.3.8
  fluttertoast: ^3.1.3
  carousel_slider: ^1.3.0
  pdf: ^1.5.0
  permission_handler: 4.4.0+hotfix.1
  url_launcher: 5.4.2
  flutter_web_auth: ^0.1.3
  webview_flutter: ^0.3.19+8
  flutter_webview_plugin: ^0.3.10+1
  introduction_screen: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - insightqlogo.png

  fonts:
    - family: MyFont
      fonts:
        - asset: assets/Fonts/sspu.ttf